# ==========================================
# SATIRFETCH CONFIG
# ==========================================


# ==========================================
# IMAGE
# ==========================================

SHOW_IMAGE=true

IMAGE_PATH="$HOME/.config/satirfetch/fetch.jpg"

IMAGE_WIDTH=24
IMAGE_HEIGHT=10


# ==========================================
# SYSTEM INFORMATION
# ==========================================

SHOW_DISTRO=true
SHOW_ANDROID=true

SHOW_KERNEL=false
SHOW_ARCH=true

SHOW_PACKAGES=true

SHOW_SHELL=true
SHOW_WM=true

SHOW_MEMORY=true
SHOW_UPTIME=true

SHOW_TERMUX=true

SHOW_TIME=true


# ==========================================
# ACTIVITY
# ==========================================

SHOW_STREAK=true
SHOW_TRACE=true
SHOW_TODAY=true

TRACE_DAYS=5


# ==========================================
# DISABLED
# ==========================================

# Battery
# Wi-Fi
# IP
# Brightness
# CPU
# GPU
# Disk
# Music